stages:
  - build
  - test

pytest:
  stage: test
  rules:
    # Only run tests when merge request is created (or manually from web interface)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
  image: "gitlab-registry.cern.ch/cryocluster/python-container-prebuild:mirror-python$VERSION"
  before_script:
    # needed for h5repack (usually installed on computing clusters)
    - apt-get update -qq && apt-get install -y -qq hdf5-tools
    - python -m pip install --upgrade pip
    # install cait including optional dependencies for testing
    # '--upgrade --upgrade-strategy eager' makes sure that always
    # latest versions of dependencies are installed (to catch
    # deprecations and version conflicts reliably)
    - python -m pip install --upgrade --upgrade-strategy eager .[test,clplot]
  script:
    - python -V
    - pytest --junitxml=report.xml
  parallel:
    matrix:
      - VERSION: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
  artifacts:
    when: always
    reports:
      junit: report.xml

sphinx:
  stage: test
  rules:
    # Only run tests when merge request is created (or manually from web interface)
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
  # Start from python3.11 image (python version used by readthedocs)
  image: gitlab-registry.cern.ch/cryocluster/python-container-prebuild:mirror-python3.11
  before_script:
    # install hdf5 tools for cait
    - apt-get update -qq && apt-get install -y -qq hdf5-tools
    - python -m pip install --upgrade pip
    # install cait including docs dependencies
    - python -m pip install --upgrade --upgrade-strategy eager .[docs]
  script:
    # Builds documents in runner's local directory. Discarded afterwards. 
    # If needed, we could add artifacts in the future.
    - sphinx-build -M html docs/source docs_build

build_kaniko_command:
  stage: build
  only:
    - develop
    - tags
  variables:
    IMAGE_DESTINATION: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}${FLAVOUR}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --build-arg "FLAVOUR=$FLAVOUR" --destination $IMAGE_DESTINATION 
    - echo "Image pushed successfully to ${IMAGE_DESTINATION}"
  parallel:
    # build a container including all optional dependencies and one without torch
    matrix:
      #- FLAVOUR: ['', '-slim'] # full container build started to fail mid of 2025 due to out-of-memory issues. Has to be investigated. Only building -slim container for now.
      - FLAVOUR: ['-slim']

